<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.10.18">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="[Add group members]">
<meta name="dcterms.date" content="2026-10-03">

<title>Writer identification in simulated handwriting</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: 1.5em;}
div.column{flex: auto;}
@media screen {
div.columns{gap: min(4vw, 1.5em);}
div.column{overflow-x: auto;}
}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="draft_assignment_report_files/libs/clipboard/clipboard.min.js"></script>
<script src="draft_assignment_report_files/libs/quarto-html/quarto.js" type="module"></script>
<script src="draft_assignment_report_files/libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="draft_assignment_report_files/libs/quarto-html/popper.min.js"></script>
<script src="draft_assignment_report_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="draft_assignment_report_files/libs/quarto-html/anchor.min.js"></script>
<link href="draft_assignment_report_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="draft_assignment_report_files/libs/quarto-html/quarto-syntax-highlighting-64a204ab8560d761af7679ceaba22944.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="draft_assignment_report_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="draft_assignment_report_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="draft_assignment_report_files/libs/bootstrap/bootstrap-62e2d20df198e8a01bb734742f2e28cf.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">


</head>

<body class="quarto-light">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
  <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#one-time-python-setup" id="toc-one-time-python-setup" class="nav-link active" data-scroll-target="#one-time-python-setup">One-time Python setup</a></li>
  <li><a href="#introduction" id="toc-introduction" class="nav-link" data-scroll-target="#introduction"><span class="header-section-number">1</span> Introduction</a></li>
  <li><a href="#data-exploration" id="toc-data-exploration" class="nav-link" data-scroll-target="#data-exploration"><span class="header-section-number">2</span> 1. Data exploration</a>
  <ul class="collapse">
  <li><a href="#structure-and-balance" id="toc-structure-and-balance" class="nav-link" data-scroll-target="#structure-and-balance"><span class="header-section-number">2.1</span> Structure and balance</a></li>
  <li><a href="#examples-across-writers-and-digits" id="toc-examples-across-writers-and-digits" class="nav-link" data-scroll-target="#examples-across-writers-and-digits"><span class="header-section-number">2.2</span> Examples across writers and digits</a></li>
  </ul></li>
  <li><a href="#cnn-writer-identification" id="toc-cnn-writer-identification" class="nav-link" data-scroll-target="#cnn-writer-identification"><span class="header-section-number">3</span> 2. CNN writer identification</a>
  <ul class="collapse">
  <li><a href="#split-and-model" id="toc-split-and-model" class="nav-link" data-scroll-target="#split-and-model"><span class="header-section-number">3.1</span> Split and model</a></li>
  <li><a href="#results-and-interpretation" id="toc-results-and-interpretation" class="nav-link" data-scroll-target="#results-and-interpretation"><span class="header-section-number">3.2</span> Results and interpretation</a></li>
  </ul></li>
  <li><a href="#siamese-same-writer-matching" id="toc-siamese-same-writer-matching" class="nav-link" data-scroll-target="#siamese-same-writer-matching"><span class="header-section-number">4</span> 3. Siamese same-writer matching</a>
  <ul class="collapse">
  <li><a href="#pair-construction-and-evaluation-split" id="toc-pair-construction-and-evaluation-split" class="nav-link" data-scroll-target="#pair-construction-and-evaluation-split"><span class="header-section-number">4.1</span> Pair construction and evaluation split</a></li>
  <li><a href="#network-and-contrastive-loss" id="toc-network-and-contrastive-loss" class="nav-link" data-scroll-target="#network-and-contrastive-loss"><span class="header-section-number">4.2</span> Network and contrastive loss</a></li>
  <li><a href="#results-and-interpretation-1" id="toc-results-and-interpretation-1" class="nav-link" data-scroll-target="#results-and-interpretation-1"><span class="header-section-number">4.3</span> Results and interpretation</a></li>
  </ul></li>
  <li><a href="#hyperparameter-sensitivity" id="toc-hyperparameter-sensitivity" class="nav-link" data-scroll-target="#hyperparameter-sensitivity"><span class="header-section-number">5</span> 4. Hyperparameter sensitivity</a></li>
  <li><a href="#comparison-and-discussion" id="toc-comparison-and-discussion" class="nav-link" data-scroll-target="#comparison-and-discussion"><span class="header-section-number">6</span> 5. Comparison and discussion</a>
  <ul class="collapse">
  <li><a href="#limitations" id="toc-limitations" class="nav-link" data-scroll-target="#limitations"><span class="header-section-number">6.1</span> Limitations</a></li>
  </ul></li>
  <li><a href="#reproducibility-and-collaboration" id="toc-reproducibility-and-collaboration" class="nav-link" data-scroll-target="#reproducibility-and-collaboration"><span class="header-section-number">7</span> 6. Reproducibility and collaboration</a></li>
  <li><a href="#conclusion" id="toc-conclusion" class="nav-link" data-scroll-target="#conclusion"><span class="header-section-number">8</span> Conclusion</a></li>
  <li><a href="#plagiarism-declaration" id="toc-plagiarism-declaration" class="nav-link" data-scroll-target="#plagiarism-declaration"><span class="header-section-number">9</span> Plagiarism declaration</a></li>
  <li><a href="#ai-use-statement" id="toc-ai-use-statement" class="nav-link" data-scroll-target="#ai-use-statement"><span class="header-section-number">10</span> AI use statement</a></li>
  </ul>
</nav>
</div>
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Writer identification in simulated handwriting</h1>
<p class="subtitle lead">STA5073Z Data Science for Industry — Assignment 2</p>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>[Add group members] </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">October 3, 2026</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<section id="one-time-python-setup" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="one-time-python-setup">One-time Python setup</h2>
<p>The R package <code>keras3</code> calls Python Keras. This project also contains a <code>.venv</code> directory, so the setup below explicitly selects the separate <code>r-keras</code> environment. Run this once in the R console (not in a Quarto chunk), then restart R before rendering:</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>reticulate<span class="sc">::</span><span class="fu">install_python</span>(<span class="st">"3.11.9"</span>)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>keras3<span class="sc">::</span><span class="fu">install_keras</span>(</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">envname =</span> <span class="st">"r-keras"</span>,</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">backend =</span> <span class="st">"tensorflow"</span>,</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">python_version =</span> <span class="st">"&gt;=3.9,&lt;=3.11"</span>,</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">extra_packages =</span> <span class="fu">c</span>(<span class="st">"numpy&lt;2"</span>, <span class="st">"ml-dtypes&lt;0.6"</span>)</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p>Python 3.11.9 and the Keras/TensorFlow dependencies have been installed in the current environment. The NumPy constraints match the versions required by the R <code>keras3</code> package. In a fresh R session the code below selects <code>r-keras</code>, overriding the project’s <code>.venv</code>.</p>
</section>
<section id="introduction" class="level1" data-number="1">
<h1 data-number="1"><span class="header-section-number">1</span> Introduction</h1>
<p>Writer identification asks whether an image of a digit can be assigned to the person who wrote it. This report compares two neural-network approaches on a simulated dataset: a convolutional neural network (CNN) that predicts one of 20 writer IDs, and a Siamese network trained to compare two images and decide whether they came from the same writer.</p>
<p>The dataset contains 25,000 grayscale images of size 28 × 28. Each of 20 simulated writers wrote digits 0–4 in five recording sessions, with 50 repetitions of each writer–digit–session combination. The data are simulated rather than samples of natural handwriting; conclusions therefore concern this dataset and should not be treated as evidence of performance on real handwriting.</p>
<p>We distinguish two generalization questions. For the CNN, we test whether writer identification transfers to a later session for writers represented during training. For the Siamese model, we test whether a learned matching rule transfers to writers excluded from its training pairs. These are different tasks and their scores are not directly interchangeable.</p>
</section>
<section id="data-exploration" class="level1" data-number="2">
<h1 data-number="2"><span class="header-section-number">2</span> 1. Data exploration</h1>
<section id="structure-and-balance" class="level2" data-number="2.1">
<h2 data-number="2.1" class="anchored" data-anchor-id="structure-and-balance"><span class="header-section-number">2.1</span> Structure and balance</h2>
<p>The checks below confirm the dimensions, pixel range, and number of examples in each metadata group. Counts other than the expected balanced design should be investigated before fitting models.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>[1] 25000    28    28     1</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0 1</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 6
  n_images n_writers n_digits n_sessions min_replicates max_replicates
     &lt;int&gt;     &lt;int&gt;    &lt;int&gt;      &lt;int&gt;          &lt;int&gt;          &lt;int&gt;
1    25000        20        5          5              1             50</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 2
  min_per_cell max_per_cell
         &lt;int&gt;        &lt;int&gt;
1           50           50</code></pre>
</div>
</div>
</section>
<section id="examples-across-writers-and-digits" class="level2" data-number="2.2">
<h2 data-number="2.2" class="anchored" data-anchor-id="examples-across-writers-and-digits"><span class="header-section-number">2.2</span> Examples across writers and digits</h2>
<p>The plot shows one randomly selected example for each combination of five sampled writers and the five digits, all from session 1. The next plot holds writer and digit fixed while showing examples from each session. Inspect these figures after rendering and describe visible similarities and differences; the code does not assume in advance which digits are most distinctive.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="draft_assignment_report_files/figure-html/unnamed-chunk-3-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="draft_assignment_report_files/figure-html/unnamed-chunk-4-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>In the rendered report, describe any visible variation in stroke shape, slant, thickness, spacing, or consistency across sessions. Also note any limitations visible in the images. Because the data are simulated, the design may not capture the full range of natural writing variation, scanning conditions, or demographic diversity.</p>
</section>
</section>
<section id="cnn-writer-identification" class="level1" data-number="3">
<h1 data-number="3"><span class="header-section-number">3</span> 2. CNN writer identification</h1>
<section id="split-and-model" class="level2" data-number="3.1">
<h2 data-number="3.1" class="anchored" data-anchor-id="split-and-model"><span class="header-section-number">3.1</span> Split and model</h2>
<p>The CNN predicts writer IDs 0–19. We train on sessions 1–3, select the dropout setting using session 4, and report the final evaluation on session 5. All writers occur in each split, which is necessary for this closed-set classification task: a 20-class classifier cannot predict a writer class it never encountered during training. Holding out sessions prevents near-duplicate observations from the same recording session appearing on both sides of the evaluation and measures transfer across sessions for known writers.</p>
<p>We compare two dropout settings as a small, prespecified hyperparameter search. Each candidate is assessed on the same validation session; session 5 is not used for model or threshold selection.</p>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: right;">dropout</th>
<th style="text-align: right;">best_validation_accuracy</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">0.2</td>
<td style="text-align: right;">0.552</td>
</tr>
<tr class="even">
<td style="text-align: right;">0.4</td>
<td style="text-align: right;">0.594</td>
</tr>
</tbody>
</table>
</div>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: right;">digit</th>
<th style="text-align: right;">accuracy</th>
<th style="text-align: right;">n</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">0</td>
<td style="text-align: right;">0.580</td>
<td style="text-align: right;">1000</td>
</tr>
<tr class="even">
<td style="text-align: right;">1</td>
<td style="text-align: right;">0.498</td>
<td style="text-align: right;">1000</td>
</tr>
<tr class="odd">
<td style="text-align: right;">2</td>
<td style="text-align: right;">0.577</td>
<td style="text-align: right;">1000</td>
</tr>
<tr class="even">
<td style="text-align: right;">3</td>
<td style="text-align: right;">0.683</td>
<td style="text-align: right;">1000</td>
</tr>
<tr class="odd">
<td style="text-align: right;">4</td>
<td style="text-align: right;">0.675</td>
<td style="text-align: right;">1000</td>
</tr>
</tbody>
</table>
</div>
</div>
</section>
<section id="results-and-interpretation" class="level2" data-number="3.2">
<h2 data-number="3.2" class="anchored" data-anchor-id="results-and-interpretation"><span class="header-section-number">3.2</span> Results and interpretation</h2>
<p>The overall test accuracy is 0.603; chance accuracy for 20 equally represented classes is 0.05. Accuracy is the fraction of session-5 images assigned to the correct writer. In this run, digit 3 had the highest digit-specific accuracy (0.683), while digit 1 had the lowest (0.498). These are descriptive results from one split and one initialization; discuss them alongside the example images rather than treating the ranking as an inherent property of those digits.</p>
<p>This is a closed-set result: the test writers are known to the model, but their session-5 samples are held out. It does not estimate performance on a new person. Accuracy can also hide which writers are confused with one another; use the confusion matrix below to identify any systematic errors.</p>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 3%">
<col style="width: 3%">
<col style="width: 5%">
<col style="width: 5%">
<col style="width: 3%">
<col style="width: 3%">
<col style="width: 5%">
<col style="width: 5%">
<col style="width: 3%">
<col style="width: 5%">
<col style="width: 3%">
<col style="width: 5%">
<col style="width: 5%">
<col style="width: 5%">
<col style="width: 5%">
<col style="width: 5%">
<col style="width: 5%">
<col style="width: 5%">
<col style="width: 5%">
<col style="width: 5%">
<col style="width: 5%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: right;">0</th>
<th style="text-align: right;">1</th>
<th style="text-align: right;">2</th>
<th style="text-align: right;">3</th>
<th style="text-align: right;">4</th>
<th style="text-align: right;">5</th>
<th style="text-align: right;">6</th>
<th style="text-align: right;">7</th>
<th style="text-align: right;">8</th>
<th style="text-align: right;">9</th>
<th style="text-align: right;">10</th>
<th style="text-align: right;">11</th>
<th style="text-align: right;">12</th>
<th style="text-align: right;">13</th>
<th style="text-align: right;">14</th>
<th style="text-align: right;">15</th>
<th style="text-align: right;">16</th>
<th style="text-align: right;">17</th>
<th style="text-align: right;">18</th>
<th style="text-align: right;">19</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">0</td>
<td style="text-align: right;">81</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">18</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">54</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">22</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">5</td>
<td style="text-align: right;">68</td>
</tr>
<tr class="even">
<td style="text-align: left;">1</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">202</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">45</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="odd">
<td style="text-align: left;">2</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">199</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">48</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="even">
<td style="text-align: left;">3</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">79</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">70</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">32</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">21</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">7</td>
<td style="text-align: right;">41</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="odd">
<td style="text-align: left;">4</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">50</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">150</td>
<td style="text-align: right;">50</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="even">
<td style="text-align: left;">5</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">200</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">50</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="odd">
<td style="text-align: left;">6</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">221</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">26</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="even">
<td style="text-align: left;">7</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">51</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">99</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">99</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="odd">
<td style="text-align: left;">8</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">6</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">42</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">149</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">53</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="even">
<td style="text-align: left;">9</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">249</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="odd">
<td style="text-align: left;">10</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">242</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="even">
<td style="text-align: left;">11</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">48</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">200</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">2</td>
</tr>
<tr class="odd">
<td style="text-align: left;">12</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">83</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">11</td>
<td style="text-align: right;">48</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">73</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">35</td>
</tr>
<tr class="even">
<td style="text-align: left;">13</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">156</td>
<td style="text-align: right;">50</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">44</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="odd">
<td style="text-align: left;">14</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">50</td>
<td style="text-align: right;">149</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">51</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="even">
<td style="text-align: left;">15</td>
<td style="text-align: right;">41</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">31</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">14</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">104</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">20</td>
<td style="text-align: right;">40</td>
</tr>
<tr class="odd">
<td style="text-align: left;">16</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">250</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="even">
<td style="text-align: left;">17</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">247</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="odd">
<td style="text-align: left;">18</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">50</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">200</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="even">
<td style="text-align: left;">19</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">86</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">161</td>
</tr>
</tbody>
</table>
</div>
</div>
</section>
</section>
<section id="siamese-same-writer-matching" class="level1" data-number="4">
<h1 data-number="4"><span class="header-section-number">4</span> 3. Siamese same-writer matching</h1>
<section id="pair-construction-and-evaluation-split" class="level2" data-number="4.1">
<h2 data-number="4.1" class="anchored" data-anchor-id="pair-construction-and-evaluation-split"><span class="header-section-number">4.1</span> Pair construction and evaluation split</h2>
<p>The Siamese experiment uses writer-disjoint splits: 12 writers for training, four for validation, and four for testing. Thus no writer represented in validation or test pairs contributes images to training pairs. This evaluates whether the matching rule transfers to writers absent from its training pairs; it is distinct from the CNN’s known-writer session-transfer question.</p>
<p>Each pair contains the same digit on both sides, controlling digit identity. Positive pairs use two distinct images from the same writer and digit; negative pairs use images from two different writers but the same digit. The training, validation, and test pair sets are balanced between positive and negative labels. A pair’s session combination is sampled from the available images, so the test set includes session variation.</p>
</section>
<section id="network-and-contrastive-loss" class="level2" data-number="4.2">
<h2 data-number="4.2" class="anchored" data-anchor-id="network-and-contrastive-loss"><span class="header-section-number">4.2</span> Network and contrastive loss</h2>
<p>Both branches share one encoder. The network is trained with contrastive loss: same-writer pairs (label 1) are encouraged to have small embedding distances, while different-writer pairs (label 0) are penalized when their distance is below a margin of 1. The model outputs the difference between the two embeddings; the loss and evaluation convert this to Euclidean distance.</p>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;">metric</th>
<th style="text-align: right;">value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Accuracy</td>
<td style="text-align: right;">0.841</td>
</tr>
<tr class="even">
<td style="text-align: left;">Balanced accuracy</td>
<td style="text-align: right;">0.841</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Sensitivity (same writer)</td>
<td style="text-align: right;">0.925</td>
</tr>
<tr class="even">
<td style="text-align: left;">Specificity (different writer)</td>
<td style="text-align: right;">0.757</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Validation-selected distance threshold</td>
<td style="text-align: right;">0.595</td>
</tr>
</tbody>
</table>
</div>
</div>
</section>
<section id="results-and-interpretation-1" class="level2" data-number="4.3">
<h2 data-number="4.3" class="anchored" data-anchor-id="results-and-interpretation-1"><span class="header-section-number">4.3</span> Results and interpretation</h2>
<p>On pairs from writers excluded from model training, test balanced accuracy is 0.841 at a distance threshold selected using validation writers only. Sensitivity is the fraction of same-writer pairs correctly accepted; specificity is the fraction of different-writer pairs correctly rejected. Balanced accuracy gives equal weight to these two rates. The threshold is selected on validation data and then held fixed for test evaluation.</p>
<p>This matching experiment is closer to verification of previously unseen writers than the CNN experiment, but it uses only four test writers and sampled pairs. Results may vary with the writer split and pair sample. They should be interpreted alongside the pair-construction protocol, not as a universal biometric error rate.</p>
</section>
</section>
<section id="hyperparameter-sensitivity" class="level1" data-number="5">
<h1 data-number="5"><span class="header-section-number">5</span> 4. Hyperparameter sensitivity</h1>
<p>For the CNN, the two dropout candidates and their session-4 validation accuracies are reported above. The chosen model is the one with the higher validation accuracy. The test set is evaluated only after selection. The difference between the two validation scores provides a limited sensitivity check; it is not a comprehensive search and does not account for variation across random seeds.</p>
<p>For the Siamese model, we fixed the architecture and contrastive margin to keep the comparison bounded. A further study could vary the margin or embedding dimension, but would need to select settings only on validation writers. Avoid repeated test-set tuning.</p>
</section>
<section id="comparison-and-discussion" class="level1" data-number="6">
<h1 data-number="6"><span class="header-section-number">6</span> 5. Comparison and discussion</h1>
<p>The CNN answers “which known writer produced this image?” and the Siamese model answers “do these two images share a writer?” The CNN test accuracy (0.603) is measured on later-session images from known writers; the Siamese balanced accuracy (0.841) is measured on pairs from writers excluded from training. Because the split designs and prediction targets differ, the scores should not be ranked as though they measured identical performance.</p>
<p>Use the digit-specific CNN results to identify which digits were easier for writer classification in this experiment. Explain the observed pattern using the image examples, while noting that each digit has its own geometry and that the same-digit pairing in the Siamese task deliberately controls for digit identity. Do not claim that a digit is inherently more writer-informative beyond this simulated dataset and evaluation.</p>
<p>The CNN split places sessions 1–3 in training and session 5 in testing, with session 4 for model selection. The Siamese pair construction samples images across the available sessions for the held-out writers. Discuss whether the displayed samples suggest session-related changes, and be cautious: this design does not provide a separate numerical estimate of the effect of session on Siamese matching. A direct session-effect analysis would require a prespecified comparison of within-session and cross-session pairs.</p>
<section id="limitations" class="level2" data-number="6.1">
<h2 data-number="6.1" class="anchored" data-anchor-id="limitations"><span class="header-section-number">6.1</span> Limitations</h2>
<ul>
<li>The images are simulated; performance may not transfer to real handwriting.</li>
<li>There are only 20 writers. The Siamese writer-disjoint test set contains four writers, so its result can be sensitive to which writers are held out.</li>
<li>Pair observations share images and writers, so pairs are not independent. Pair-level accuracy does not imply the same precision as an evaluation over a large independent population.</li>
<li>Only two CNN dropout settings were tested, with one random seed. Report the resulting validation values and treat small differences cautiously.</li>
<li>The CNN and Siamese evaluations target different forms of generalization, as described above.</li>
</ul>
</section>
</section>
<section id="reproducibility-and-collaboration" class="level1" data-number="7">
<h1 data-number="7"><span class="header-section-number">7</span> 6. Reproducibility and collaboration</h1>
<p>The project repository should contain this Quarto source, the code and data-loading instructions needed to reproduce the analysis, and the rendered site source. Keep the supplied dataset in the repository only if course rules permit it. Group members should use branches and pull requests, with each member’s contribution recorded in the submission text file.</p>
<p>The code sets seeds for R and Keras/TensorFlow. Some TensorFlow operations may still be nondeterministic. Record the R, Keras, and TensorFlow versions used for the final run and retain the rendered report and relevant training outputs.</p>
<p>Before submission, add the group members and roles to the required text file, include the GitHub Pages URL and source repository URL, and confirm the Quarto site is published from that repository. The group presentation is a separate deliverable (maximum 20 minutes); all members must attend and present.</p>
</section>
<section id="conclusion" class="level1" data-number="8">
<h1 data-number="8"><span class="header-section-number">8</span> Conclusion</h1>
<p>This analysis compares closed-set writer classification with pairwise same-writer matching on simulated 28 × 28 digit images. The reported results quantify performance under explicit session-based and writer-disjoint evaluation designs. The final interpretation should be grounded in the rendered examples and computed tables, and should avoid extrapolating beyond the simulated data.</p>
</section>
<section id="plagiarism-declaration" class="level1" data-number="9">
<h1 data-number="9"><span class="header-section-number">9</span> Plagiarism declaration</h1>
<blockquote class="blockquote">
<p>[Group: insert the course-required plagiarism declaration in your own words and confirm that it is accurate for every group member.]</p>
</blockquote>
</section>
<section id="ai-use-statement" class="level1" data-number="10">
<h1 data-number="10"><span class="header-section-number">10</span> AI use statement</h1>
<p>The course requires disclosure, task by task, of the AI tools used, what they were used for, how outputs were checked, and how much AI output was retained. Complete this statement accurately before submission. This document was drafted with AI assistance; the group should describe its actual use of AI for data exploration, model code, interpretation, and editing, including which parts were independently run, checked, changed, or discarded. Do not retain statements about tools or verification that did not occur.</p>
<p>For this draft, ChatGPT through Copilot SDK was used to create the report structure, propose analysis code and evaluation designs, diagnose Python/Keras setup failures, and revise the contrastive-loss implementation. The assistant installed a compatible Python/Keras/TensorFlow environment, executed the report on the provided dataset, and rendered the Quarto document. The group must review the code, figures, performance values, and interpretation, rerun the report on its own setup, and update this disclosure to include all AI tools used by the group.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th>Assignment task</th>
<th>AI assistance in this draft</th>
<th>Verification completed so far</th>
<th>Draft output retained</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>1. Explore images and metadata</td>
<td>Suggested metadata summaries and plots of writer, digit, and session examples.</td>
<td>Dataset checks and plots were executed by the assistant; the group still needs to inspect them and write its own observations.</td>
<td>Code and generated figures; observations require group review.</td>
</tr>
<tr class="even">
<td>2. CNN writer identification</td>
<td>Proposed a CNN, a session-based split, dropout comparison, and per-digit evaluation.</td>
<td>Both dropout candidates were fitted; validation selection and session-5 predictions were produced. The group should review the modeling choices and rerun.</td>
<td>CNN code, tuning table, confusion matrix, and test metrics.</td>
</tr>
<tr class="odd">
<td>3. Siamese matching</td>
<td>Proposed writer-disjoint pairs, same-digit controls, a shared encoder, and contrastive loss.</td>
<td>Pair constraints were checked on sampled pairs; the network was fitted and test metrics were generated. The loss also passed a small training smoke test.</td>
<td>Pair/model code and generated test metrics.</td>
</tr>
<tr class="even">
<td>4. Train/validation/test strategy</td>
<td>Drafted explanations of session-held-out CNN evaluation and writer-held-out Siamese evaluation.</td>
<td>Split and pair-generation code ran; the group should confirm that these answer its intended generalization questions.</td>
<td>Split code and explanation, subject to group approval.</td>
</tr>
<tr class="odd">
<td>5. Hyperparameter optimization</td>
<td>Proposed comparing two CNN dropout values using validation accuracy.</td>
<td>Two dropout settings were compared on validation data in one run; no repeated-seed uncertainty analysis was done.</td>
<td>Tuning code and validation results.</td>
</tr>
<tr class="even">
<td>6. Compare models</td>
<td>Added a discussion framework and cautions about comparing different evaluation targets.</td>
<td>Metrics from both experiments were generated; the group must interpret them and avoid treating the distinct scores as directly comparable.</td>
<td>Draft comparison with metrics, subject to review.</td>
</tr>
<tr class="odd">
<td>7. Git/GitHub collaboration</td>
<td>Added a reminder of the required repository workflow and submission details.</td>
<td>No repository workflow or group roles have been checked.</td>
<td>Reminder text, to be updated with the group’s actual process.</td>
</tr>
<tr class="even">
<td>8. Report</td>
<td>Generated and revised this Quarto draft.</td>
<td>All R chunks parsed and the Quarto report rendered; the group must review the rendered output, word limit, and claims.</td>
<td>Draft source and rendered HTML, not yet submission-ready.</td>
</tr>
<tr class="odd">
<td>9. GitHub Pages</td>
<td>Included a publication checklist.</td>
<td>No site has been published or verified.</td>
<td>Checklist text only.</td>
</tr>
</tbody>
</table>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>